# Generated by Django 3.1.6 on 2021-02-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alias',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
