# Generated by Django 3.1.6 on 2021-02-10 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alias', '0002_auto_20210208_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'ordering': ('-target',)},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ('-title',)},
        ),
        migrations.AlterField(
            model_name='alias',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
