# Generated by Django 3.1.6 on 2021-02-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alias', '0003_auto_20210210_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
